# C.Q 1.4: Which was the position of team England in Round 1?

PREFIX list:<http://www.ontologydesignpatterns.org/cp/owl/list.owl#>
PREFIX bag:<http://www.ontologydesignpatterns.org/cp/owl/bag.owl#>
PREFIX dbr:<http://dbpedia.org/resource/>
PREFIX :<http://bdi.si.ehu.eus/bdi/ontologies/LOP/tests/sixnations2023/>
SELECT (COUNT (?item) AS ?pos)  WHERE{
    :Round_1 bag:hasItem ?item .
    ?item list:nextItem*/bag:itemContent dbr:England_national_rugby_union_team
}
