# C.Q 1.1: Which are the teams in Round 1?

PREFIX bag:<http://www.ontologydesignpatterns.org/cp/owl/bag.owl#>
PREFIX :<http://bdi.si.ehu.eus/bdi/ontologies/LOP/tests/sixnations2023/>
SELECT ?team WHERE{
    :Round_1 bag:hasItem/bag:itemContent ?team
}



