# C.Q 2.7: In how many rounds of fixtures was team England after team France during the 2023 Six Nations Championship?

PREFIX list:<http://www.ontologydesignpatterns.org/cp/owl/list.owl#>
PREFIX bag:<http://www.ontologydesignpatterns.org/cp/owl/bag.owl#>
PREFIX dbr:<http://dbpedia.org/resource/>
PREFIX :<http://bdi.si.ehu.eus/bdi/ontologies/LOP/tests/sixnations2023/>
SELECT (COUNT (?round) AS ?numRounds)  WHERE{
    :sixnations2023 bag:hasItem/bag:itemContent ?round .
    ?round bag:hasItem ?item1 .
    ?item1 bag:itemContent dbr:England_national_rugby_union_team .
    ?round bag:hasItem ?item2 .
    ?item2 bag:itemContent dbr:France_national_rugby_union_team .
    ?item1 list:previousItem+ ?item2
}
